---
title: "R Notebook"
author: "olly-mapps"
---

# Libraries

```{r}
library(tidyverse)
```

# Loading Data 

```{r}
poss_data <- read.csv("../data/_data/possession_data.csv")
```

```{r}
poss_data
```

# Models

We first define our test and train sets

```{r}
sample <- sample(c(TRUE, FALSE), nrow(poss_data), replace=TRUE, prob=c(0.8,0.2))
train  <- poss_data[sample, ]
test   <- poss_data[!sample, ]
```

```{r}
Y.train <- train %>% dplyr::select(where(is.numeric) & ends_with("_change"), -Att_Take_change)

X.train <- train %>% dplyr::select(-all_of(colnames(Y.train)), -X, -Player_from)

X.train.names <- X.train %>% dplyr::select(-Comp_2_change) %>% colnames() 

```

```{r}
X.train.names
```

```{r}
models <- X.train %>% group_by(Comp_2_change) %>% 
              do(model = lm(Att_Take_change ~ X.train.names, data = .))
```

```{r}
models$model[[1]]
```
```{r}
la_liga_pred <- predict(models$model[[1]], test)
```

```{r}
cbind(test, la_liga_pred) %>% dplyr::select("Player_from", "Att_Take_change", "la_liga_pred")
```

